apiVersion: v1
kind: Service
metadata:
  name: vote-back-public-repo
  labels:
    name: vote-back
spec:
  ports:
  - port: 6379
  selector:
    app: vote-back
---
apiVersion: v1
kind: Service
metadata:
  name: vote-front-public-repo
  labels:
    name: vote-front
spec:
  ports:
  - port: 80
  selector:
    app: vote-front